# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d19ac7fdb859df4f7fbe8bb74c4b8807811a96285b978c92ac978666f46826065948789ecc41a54c3ef121563fd43fe11200bac33efe1403dacc65c03c1db8

test:
  secret_key_base: 48da9293a8c6ef8ba87528ff60f9dbc2ca657b4e3daee99ded028654284d4fac595264277d6c4d8f81c077eb031455ca0339cb94761836a74bae9f2aa907ca52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
